### ISSUE TITLE
Add Moderator, VIP and Broadcaster to the list of Access State

### ISSUE THREAD

**Issue by rochacbruno** [builders-club/vscode-twitch-themer#133]
Is it possible to have `VIP` , `Moderator` and `Broadcaster` on this list?

![](https://user-images.githubusercontent.com/1228996/59153253-bf03f080-8a1a-11e9-9dc3-9fe92b3cb413.png)

**Comment by MichaelJolley** [comment]
That should be fairly simple to implement. I like it!

@all-contributors please add @rochacbruno for ideas
