### ISSUE TITLE
Add setting to change the command from !theme to anything else

### ISSUE THREAD

**Issue by rochacbruno** [builders-club/vscode-twitch-themer#134]
Hi,

When I am streaming in Portuguese it is nice to have `!tema` or `!color` in place of `!theme` is it possible to have a setting to customize the command trigger or maybe add aliases.

**Comment by MichaelJolley** [comment]
That should be doable.  We'd likely need a few different ones:

- theme
- install
- current
- random
- dark
- light

**Comment by MichaelJolley** [comment]
@parithon I just realized I merged that PR but forgot to request an update to the CHANGELOG. Can you get that in?
