### ISSUE TITLE
Cant't sign in anymore

### ISSUE THREAD

**Issue by novas1r1** [builders-club/vscode-twitch-themer#177]
Hi,
I used the twitch themer successfully few months ago but now it doesnt work anymore.

I tried Sign out, sign in, uninstalled the whole extension, restarted multiple times but it's still not reacting to my commands. In the bottom bar it says I'm disconnected and no matter what I do, it won't change. If I sign out and sign in again a browser windows opens where I can access the connection to my twitch account. After this was successful it tells me I can close the page but still no connection change from the extension. 

![image](https://user-images.githubusercontent.com/2575205/147506629-9f39f02a-281b-44ee-9e1b-bfc6c35c32e0.png)

Can someone help :(?

Best regards
Verry

**Comment by MichaelJolley** [comment]
Thanks for reporting this. Unfortunately, I can't duplicate it. I hate to say the stereotypical "it works on my machine" so I spun up a VM with a clean Windows and VS Code install and it works okay. One thing I noticed, you may get a pop-up from Windows asking for permission to let VS Code access your network. You must select yes/okay for it to work.

Is this still occurring? I recently started streaming again and have been using it this week with no problems. Any other details you may could provide?

**Comment by novas1r1** [comment]
Hi @MichaelJolley 
Sorry for the late response, I haven't had a ccess to my computer.

So I tried it again today and what happens if I'm trying to sign in there is a browser window openening which is instantly shutting down again. It's so fast I can't even see what stands in there ^^. I tried it multiple times but it's not authenticating correctly in Twitch - at least I'm always disconnected with the Twitch themer.

Is there a way to access the logs?

**Comment by MichaelJolley** [comment]
Hiya @novas1r1. Sorry for my late response. I refactored a LOT of this extension and hopefully it will work for you now. Let me know if you still have problems and we can reopen this issue.

On the logs, yes, in the Output panel, select Twitch Themer to see a log of events, including all chat message & commands.

![image](https://github.com/builders-club/vscode-twitch-themer/assets/1228996/d050c9c8-ce01-473f-b761-469468917cae)
